### ISSUE TITLE
Psaní v CZ

### ISSUE THREAD

**Issue by ShiftyDC** [k13132/phdthesis#1]
Dobrý den, rád bych se touto formou dotázal, zda lze nějak upravit úvodní stranu u thesis-final.tex do CZ jazyka + další následující stranu"Declaration"? Buďto jsem slepý, ale nepovedlo se mi nikde najít LaTex kód pojící se k těmto stranám. Rád bych tuto šablonu použil pro psaní diplomové práce. 
Děkuji, Adam.

**Comment by zokl** [comment]
Dobrý den, šablona je plně konfigurovatelná. Jen upozorňuji že použité logo už neodpovídá oficiálnímu logu ČVUT. Chtělo by to aktualizovat. Pokud chcete, dotoho. Rádi vystavíme aktuální verzi.
